name: telegram message

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a job called "build" adn "log-github-event-goodies"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        with:
          # checkout full tree
          fetch-depth: 0
      - run: |
          git log --pretty=format:"'\`%h\`' - %an, %ar : %s" ${{ github.event.before }}..${{ github.sha }} > COMMITS_LIST

      - name: Set outputs
        id: commits_list
        run: |
          COMMITS_STRING=$(cat COMMITS_LIST)
          COMMITS_STRING="${COMMITS_STRING//'%'/'%25'}"
          COMMITS_STRING="${COMMITS_STRING//$'\n'/'%0A'}"
          COMMITS_STRING="${COMMITS_STRING//$'\r'/'%0D'}"
          echo "::set-output name=full_list::$COMMITS_STRING"

      - name: send default message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          disable_web_page_preview: true
          format: markdown
          message: |
            *[${{ github.event.repository.name }}:${{ github.ref_name }}]* by *${{ github.actor }}*:

            ${{ steps.commits_list.outputs.full_list }}

            [See changes](${{ github.event.commits[0].url }})

  # log-github-event-goodies:
  #   name: "LOG Everything on GitHub Event"
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Logging
  #       run: |
  #         echo "${{ toJSON( github.event ) }}"
