name: telegram message

# Controls when the workflow will run
on:
  push:
    branches:
      - '**'
  pull_request:
    types:
      - opened
      - synchronize
  create: {}
  delete: {}
  issues: {}
  workflow_call:
    inputs:
      additional-text:
        description: 'Additional text passed from the caller workflow'
        required: false
        type: string
    secrets:
      TELEGRAM_TO:
        description: 'Telegram ID passed from the caller workflow'
        required: true
      TELEGRAM_TOKEN:
        description: 'Telegram token passed from the caller workflow'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a job called "build" adn "log-github-event-goodies"
  push:

    if: ${{ github.event.commits != null && inputs.additional-text == null }}

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Get commits
        id: get_commits
        uses: actions/checkout@v4
        with:
          # checkout full tree
          fetch-depth: 0

      - name: Work with commits
        id: with_commits
        run: |
          # Подготовка заголовка
          HEADER="<b>[${{ github.event.repository.name }}:${{ github.ref_name }}]</b>"

          if [ "${{ github.event.before }}" == "0000000000000000000000000000000000000000" ]; then
            git fetch origin HEAD
            git checkout HEAD
            readarray=()
            while IFS= read -r line; do
                readarray+=("$line")
            done < <(git log --pretty=format:"'<code>%h</code>' - %an, %ar : %s" HEAD..${{ github.sha }})
            echo "before=${{ github.sha }}" >> $GITHUB_OUTPUT
          else
            readarray=()
            while IFS= read -r line; do
                readarray+=("$line")
            done < <(git log --pretty=format:"'<code>%h</code>' - %an, %ar : %s" ${{ github.event.before }}..${{ github.sha }})
            echo "before=${{ github.event.before }}..${{ github.sha }}" >> $GITHUB_OUTPUT
          fi

          COMMITS_ARRAY=("${readarray[@]}")
          TOTAL_COMMITS=${#COMMITS_ARRAY[@]}
          
          if [ "$TOTAL_COMMITS" = "1" ]; then
              COMMITS_TEXT="$TOTAL_COMMITS new commit"
          else
              COMMITS_TEXT="$TOTAL_COMMITS new commits"
          fi

          HEADER="$HEADER <b><a href=\"https://github.com/${{ github.repository }}/compare/${{ steps.with_commits.outputs.before }}\">$COMMITS_TEXT</a></b> by <b><a href=\"https://github.com/${{ github.actor }}\">${{ github.actor }}</a></b>"

          # Разбиваем коммиты на части по 40 штук
          PARTS=()
          CHUNK=""
          COUNT=0
          MAX_COMMITS=40

          for COMMIT in "${COMMITS_ARRAY[@]}"; do
            if [ $COUNT -eq 0 ]; then
              CHUNK="$HEADER\n\n"
            fi
            CHUNK+="$COMMIT\n"
            COUNT=$((COUNT + 1))
            
            if [ $COUNT -eq $MAX_COMMITS ]; then
              PARTS+=("$CHUNK")
              COUNT=0
            fi
          done

          # Добавляем оставшиеся коммиты, если есть
          if [ $COUNT -gt 0 ]; then
            PARTS+=("$CHUNK")
          fi

          # Записываем части в выходные данные
          for INDEX in "${!PARTS[@]}"; do
            echo "part_$INDEX<<EOF" >> $GITHUB_OUTPUT
            echo "${PARTS[$INDEX]}" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          done
          echo "total_parts=${#PARTS[@]}" >> $GITHUB_OUTPUT
          echo $GITHUB_OUTPUT

      - name: Send messages to Telegram
        if: ${{ steps.with_commits.outputs.total_parts != '' }}
        run: |
          # Выведем все outputs для отладки
          echo "All outputs:"
          echo "${{ steps.with_commits.outputs }}"
          echo "---"
          
          for i in $(seq 0 $((${{ steps.with_commits.outputs.total_parts }} - 1))); do
            PART_NAME="part_${i}"
            echo "Looking for part: $PART_NAME"
            
            # Сохраним весь вывод grep в переменную и выведем его
            GREP_OUTPUT=$(echo "${{ steps.with_commits.outputs }}" | grep -A2 "^${PART_NAME}<<EOF$")
            echo "Grep output:"
            echo "$GREP_OUTPUT"
            echo "---"
            
            # Получаем сообщение с измененным способом извлечения контента
            MESSAGE=$(echo "${{ steps.with_commits.outputs }}" | sed -n "/^${PART_NAME}<<EOF$/,/^EOF$/p" | grep -v "EOF")
            echo "Message content:"
            echo "$MESSAGE"
            echo "---"
            
            echo "Sending part $i to Telegram"
            curl -v -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
              -d chat_id="${{ secrets.TELEGRAM_TO }}" \
              -d parse_mode="HTML" \
              -d text="$MESSAGE" \
              -d disable_web_page_preview="true"
          done

  create:

    if: ${{ github.event.master_branch != null && github.event.commits == null }}

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Send message to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          disable_web_page_preview: true
          format: markdown
          message: |
            *[${{ github.event.repository.name }}:${{ github.ref_name }}]* by *${{ github.actor }}*:

            added branch [${{ github.event.ref }}](https://github.com/${{ github.repository }}/tree/${{ github.event.ref }}) from [${{ github.event.master_branch }}](https://github.com/${{ github.repository }}/tree/${{ github.event.master_branch }})

  pull_request:

    if: ${{ github.event.pull_request != null }}

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Send message to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          disable_web_page_preview: true
          format: markdown
          message: |
            *[${{ github.event.repository.name }}:${{ github.ref_name }}]* by *${{ github.actor }}*:

            pull request from [${{ github.event.pull_request.head.ref }}](https://github.com/${{ github.repository }}/tree/${{ github.event.head.ref }}) to [${{ github.event.pull_request.base.ref }}](https://github.com/${{ github.repository }}/tree/${{ github.event.base.ref }}) with comment:
            ${{ github.event.pull_request.body }}

  delete:

    if: ${{ github.event.master_branch == null && github.event.commits == null && github.event.pull_request == null && inputs.additional-text == null }}

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Send message to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          disable_web_page_preview: true
          format: markdown
          message: |
            *[${{ github.event.repository.name }}:${{ github.ref_name }}]* by *${{ github.actor }}*:

            branch '`${{ github.event.ref }}`' is deleted

  get_last_commit:
    if: ${{ inputs.additional-text != null }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update repository
        run: git pull

      - name: Get last commit information
        id: get_commits
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
          COMMIT_AUTHOR=$(git log -1 --pretty=format:"%an")
          COMMIT_HASH=$(git rev-parse HEAD)
          echo "message=$COMMIT_MESSAGE" >> $GITHUB_OUTPUT
          echo "author=$COMMIT_AUTHOR" >> $GITHUB_OUTPUT
          echo "hash=$COMMIT_HASH" >> $GITHUB_OUTPUT

      - name: Set outputs
        id: set_outputs
        # The part of this solution to focus on is that we’re substituting the %, \n, and \r characters
        run: |
          additional_text=$(echo "${{ inputs.additional-text || '' }}" | base64 -d)
          if [ "$additional_text" != "" ]; then
            # Форматируем текст с переносами строк
            additional_text=$(echo -e "$additional_text")
            
            # Debug: print the formatted text
            echo "Formatted additional_text:"
            echo "$additional_text"
            
            echo "additional_text<<EOF" >> $GITHUB_OUTPUT
            echo "" >> $GITHUB_OUTPUT
            echo "<pre>$additional_text" >> $GITHUB_OUTPUT
            echo "</pre>" >> $GITHUB_OUTPUT
            echo "" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi

      - name: Send message to Telegram
        if: ${{ steps.get_commits.outputs.hash != '' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          disable_web_page_preview: true
          format: html
          message: |
            <b>[${{ github.event.repository.name }}:${{ github.ref_name }}]</b> <b><a href="https://github.com/${{ github.repository }}/commit/${{ steps.get_commits.outputs.hash }}">Last commit</a></b> by <b>${{ steps.get_commits.outputs.author }}</b>
            ${{ steps.set_outputs.outputs.additional_text }}
            ${{ steps.get_commits.outputs.message }}


  log-github-event-goodies:
    name: "LOG Everything on GitHub Event"
    runs-on: ubuntu-latest
    steps:
      - name: Logging
        run: |
          echo "${{ toJSON( github.event ) }}"
